### ISSUE TITLE
cdn.jsdelivr.net blocked can't get github-sync.umd.js

### ISSUE THREAD

**Issue by droddy** [boydaihungst/altair-graphql-plugin-github-sync#2]
Hello, I'm trying to use the plugin but the icon to configure never appears. When I observer the network I see that I'm being prevented from loading anything from cdn.jsdelivr.net.

Is there some way to get this from any other cdn?

**Comment by droddy** [comment]
Actually, it looks like it isn't my corporate network blocking. Maybe Firefox...
![image](https://user-images.githubusercontent.com/655776/174064504-7d12f24f-fa10-4cef-9ecf-0ba721dcde3e.png)

It pings and looks up just fine:
![image](https://user-images.githubusercontent.com/655776/174064649-fcf67f17-ddf9-4ce2-83d6-a4047a7ee8c2.png)

**Comment by droddy** [comment]
Yeah, works just fine in Chrome. Re-open if you want but I'll use chrome.
Thanks!

**Comment by boydaihungst** [comment]
@droddy Unfortunately. Firefox only loads scripts that are local to extension.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_Security_Policy#default_content_security_policy
